# OCD-NET therapist manual

## What is OCD-NET?

The treatment in OCD-NET is based on established treatment protocols for OCD [@foa2012], and focuses on exposure with response prevention (ERP). This means patients do most of the active treatment work away from their computer or mobile device, for example when they are performing exposure and response prevention exercises.

## Who is suitable for OCD-NET

OCD-NET has been developed to treat adult patients with OCD. In previous trials evaluating OCD-NET, participants have had comorbid conditions such as depression and anxiety. Patients may also take antidepressant medication during the course of treatment. We recommend that patients do not change the dose during the course of treatment. OCD-NET may also be delivered to patients with any level of OCD symptom severity. OCD-NET is text-based and requires sufficient reading skills and understanding of English. The intended use of OCD-NET is within a stepped-care model where patients are offered low-intensity treatments as a first step, [see the NICE-guidelines](https://www.nice.org.uk/guidance/CG31/chapter/1-Guidance#stepped-care-for-adults-young-people-and-children-with-ocd-or-bdd).

## Who is not suitable for OCD-NET

We recommend that the patient is assessed and managed according to local clinical guidelines as to whether there are indications that OCD-NET may not be a suitable treatment option. In some cases, treatment can be delayed if an issue is expected to be resolved in a timely manner, for example if a patient will have sufficient time to work on the treatment in the weeks to come. Indications that an individual is not suitable for OCD-NET include:

* Moderate to high suicidal ideations where written contact with a therapist 1-3 times per week is not enough to safely monitor and address risk.  
* Expresses low motivation, has attention deficits, or marked lethargy.  
* Does not have sufficient time (about 45min/day) to work on treatment.  
* Psychosis, bipolar disorder, untreated substance use disorder, or other severe clinical condition that might interfere with treatment.  
* Severe depression (e.g., MADRS ≥35).  
* Another ongoing psychological treatment.  

## Presenting OCD-NET as an option to the patient

It is important to stress that previous trials of OCD-NET have been conducted on patients who have actively requested internet-based treatment when giving this option. Thus, forcing someone to undertake a treatment they do not agree with is unhelpful at the very least and can also be harmful.

With that in mind, we believe there are two particularly strong arguments for the use of OCD-NET rather than face-to-face therapy: patients can access the treatment content and therapist support whenever they want to, and treatment can start right away rather than after a waiting time.

We have also found that many patients like to contribute to research and the development of new treatments. For example, most patients will see the benefit of evaluating remote treatment options.

Other suggestions:

* Write your first message on the first day of treatment to welcome the patient and notify them of ways to contact you with questions
* Provide encouragement throughout treatment to motivate the patient and establish a therapeutic working alliance

## Modules in OCD-NET

There are 10 modules in OCD-NET which patients are expected to complete in 12 weeks. Each module consists of texts and uses well established evidence-based interventions for OCD, with exposure and response prevention (ERP) being the core intervention. To progress to the next module participants have to complete homework assignments (such as reading text material, answering a quiz at the end of each module, completing worksheets, or reporting about ERP exercises) which are viewed by their therapist. A patient is ready for the next module once they have demonstrated the key knowledge and skills through homework, worksheets and/or messages to the therapist.

| **Treatment module** | **Content** | **Key knowledge and skills** |
| :--- | :--- | :--- |
| 1. Introduction to the treatment | Introduction to CBT <br> Information about OCD | Identifying obsessions and compulsions |
| 2. A CBT model of OCD | Psychological model of OCD with patient examples | Understanding the role of compulsions in maintaining OCD |
| 3. Thinking mistakes in OCD | Common cognitive biases and unhelpful interpretations of thoughts in OCD | Understanding how interpretations can exacerbate anxiety |
| 4. Introduction to ERP | Goal setting <br> Planning ERP exercises | Understanding the rationale for ERP <br> Setting specific, measurable goals for treatment |
| 5. More about ERP | Best practices in ERP | Understanding why it is important to repeat ERP exercises <br> Gradually increasing the difficulty of ERP exercises |
| 6. Imaginal exposure | Instructions to get started with imaginal exposures | Understanding when imaginal exposure is a useful ERP strategy |
| 7. Re-exposure | Undoing habitual compulsions | Applying re-exposure techniques in ERP exercises |
| 8. Difficulties during treatment | Common problems in ERP <br> Motivation traps | Problem-solving skills for common problems in ERP |
| 9. Long-term goals and values | Increasing valued behaviours <br> Aligning ERP exercises with long term values | Adding valued behaviours to weekly plan |
| 10. Summary and wrap up | Maintaining progress <br> Relapse prevention | Understanding that improvements can occur after treatment if ERP is practiced continuously |

We view modules 1,2,4 and 5 as the core modules in OCD-NET. Modules 1 and 2 consist of two essential features: the patient needs to report at least some intrusions/compulsions in the OCD diary, and the patient needs to understand the CBT model of OCD. These two features are the building blocks for the subsequent ERP exercises in module 4 and 5. We usually recommend patients to do modules 1-5 at a relatively quick pace in order to get to the active treatment as soon as possible. It is not crucial to have a detailed plan for each ERP exercise before starting; you should encourage patients to get started and fine-tune ERP exercises as they go along.

You can consider modules 3 and 6 as optional for the patient. We advise all our patients to read the text in module 3 (thinking mistakes), but if the patient does not feel that this cognitive intervention is relevant for them, we proceed directly to module 4 (ERP). Module 6 (imaginal exposure) may be beneficial for some patients but our experience is that many patients skip this intervention. Although the text is written from a habituation lens, we often tell our patients that imaginal exposure may be a tool to learn that having a thought or image is not the same as acting that way, and to tolerate uncertainty.

The number of completed modules is not an essential predictor of treatment outcomes in OCD-NET. We have two goals only: get the patient to module 5 and get the patient to do a lot of ERP exercises. Thus it is not essential that the patient progress through all modules as long as he/she does ERP and reports this frequently to the therapist. Patients will gain access to all modules at the end of treatment, and will be able to log onto the platform for one year after completing the OCD-NET treatment. Thus, the role of the therapist is to encourage the patient to do ERP exercises and help them to design and evaluate ERP exercises effectively.

Modules 6-9 can be opened in any order to fit the needs of each patient. For example, a patient might not have any use for imaginal exposure but finds that they have a hard time refraining from habitual compulsions. In that case, you may open up module 7 (re-exposure) instead of module 6 (imaginal exposure). Other patients may struggle with ERP exercises and will find module 8 (difficulties during the treatment) useful. Use your clinical judgement and discuss with your supervisor.

## Closing remarks

We hope that you have found this therapist guide useful. Our goal has been to present a few ideas about how to deliver OCD-NET effectively. These are just the first building blocks and you will likely find that adaptations are needed to your particular patients and your own style as a therapist.

We strive to continuously update and improve this material and would appreciate any feedback. You can reach us at <ocdnet.support@webcbt.se> or talk to us in person at a training session.
