# BDD-NET therapist manual

## What is BDD-NET?

BDD-NET is a therapist-guided internet-delivered cognitive behaviour therapy that consists of eight interactive modules and focuses on exposure with response prevention (ERP). This means that patients do most of the active treatment work away from their computer or mobile device, for example when they are performing ERP exercises.

### Differences between BDD-NET and other psychological treatments for BDD

BDD-NET is based on two existing treatment manuals for body dysmorphic disorder (BDD) [@veale2010; @wilhelm2013] and includes cognitive as well as behavioural techniques. Exposure and response prevention (ERP) techniques are emphasised in BDD-NET because they provide concrete exercises for patients to complete. Results from the two clinical trials of BDD-NET [@enander2014; @enander2016] suggest that ERP is an effective strategy in this guided self-help treatment. Within the ERP exercises, we suggest that therapists maximise inhibitory learning [@craske2014] by focusing on the new insights that patients get from ERP, rather than habituation.

ERP and other techniques in BDD-NET are most effective in patients with at least moderate insight into their BDD who are ready to try new behaviours. For patients with delusional BDD or those that express low commitment to change, other treatment options should be considered (see chapter 14 in @veale2010 for a discussion of these issues).

## Who is suitable for BDD-NET

BDD-NET is developed to treat adults with BDD. Patients may have comorbid conditions, for example other anxiety disorders, depression, or obsessive-compulsive disorder. Patients may also take antidepressant medication during the course of treatment. We recommend that patients do not change the dose during the course of treatment. BDD-NET may also be delivered to patients with any level of BDD symptom severity. The intended use of BDD-NET is within a stepped-care model where patients are offered low-intensity treatments as a first step, [see the NICE-guidelines](https://www.nice.org.uk/guidance/CG31/chapter/1-Guidance#stepped-care-for-adults-young-people-and-children-with-ocd-or-bdd). BDD-NET is text-based and requires sufficient reading skills and understanding of English.

## Who is not suitable for BDD-NET

We recommend that the patient is assessed and managed according to local clinical guidelines as to whether there are indications that BDD-NET may not be a suitable treatment option. In some cases, treatment can be delayed if an issue is expected to be resolved in a timely manner, for example if a patient will have sufficient time to work on the treatment in the weeks to come. Indications that an individual is not suitable for BDD-NET include:

* Moderate to high suicidal ideations where written contact with a therapist 1-3 times per week is not enough to safely monitor and address risk.  
* Expresses low motivation, has attention deficits, or marked lethargy.  
* Does not have sufficient time (about 45min/day) to work on treatment.  
* Psychosis, bipolar disorder, untreated substance use disorder, or other severe clinical condition that might interfere with treatment.  
* Severe depression (e.g., MADRS ≥35).  
* Another ongoing psychological treatment.  

## Presenting BDD-NET as an option to the patient

It is important to stress that previous trials of BDD-NET have been conducted on patients who have actively requested internet-based treatment when giving this option. Thus, forcing someone to undertake a treatment they do not agree with is unhelpful at the very least and can also be harmful. Below are aspects that therapists might want to consider before patients start BDD-NET.

### Assessing insight

Participating in internet-based treatments such as BDD-NET is voluntary, and therapists need to make sure that patients are willing to challenge their BDD in treatment. Lack of insight is common in BDD and BDD-NET is designed to work for patients that express varying degrees of insight. It is our experience that patients need to at least be willing to try out alternative behaviours during the course of treatment, even if they might still be convinced that their appearance concerns are justified at the start of treatment. 

### Managing expectations

Some patients may have expectations to be completely free from anxiety after BDD-NET, and that all that is required of them is to read and understand what is written in the treatment modules. Such expectations are discussed in module 4 (goal setting) but therapists are advised to assess whether patients are willing to challenge their BDD through exposure with response prevention and try out alternative behaviours before starting BDD-NET. If someone completely refuses to try new behaviours they are unlikely to actively participate in BDD-NET and benefit from the treatment.

### A good start in BDD-NET

Many patients with BDD find BDD-NET an interesting treatment option, particularly those who avoid many activities due to their appearance concerns. The strongest arguments in favour of ICBT treatments like BDD-NET, from a patient perspective, is that the treatment content and the therapist are accessible throughout the week, and that the treatment starts promptly after evaluation rather than after a time on a waiting list.

To give patients a positive first impression of the treatment, we suggest that therapists write their first message on the first day of treatment to welcome the patient and introduce treatment content. Provide encouragement throughout treatment to motivate the patient and establish a therapeutic working alliance. Patients sometimes struggle with crucial treatment components such as the BDD diary exposure with response prevention (ERP), and therapists should provide extra support at those points, if needed.

## Modules in BDD-NET

Below is an overview of the eight treatment modules. We recommend that therapists look at them from a patient's point of view before starting the first treatment. A patient is ready for the next module once they have demonstrated the key knowledge and skills through homework, worksheets and/or messages to the therapist.

| **Treatment module** | **Content** | **Key knowledge and skills** |
| :--- | :--- | :-- |
| 1. Introduction to BDD and the treatment | An introduction to BDD <br> Introduction to the treatment content | Identifying safety and avoidance behaviours |
| 2. A CBT model of BDD | Psychological explanation of the link between thoughts, emotions, and behaviours  | Understanding how safety and avoidance behaviours maintain BDD |
| 3. Interpretation traps | Common cognitive biases in BDD | Understanding how interpretations can exacerbate anxiety |
| 4. Introduction to ERP | Goal setting and planning of exposure with response prevention | Understanding the rationale for ERP <br> Formulating specific and measurable goals for treatment <br> Planning a first ERP exercise |
| 5. More about ERP | Doing and evaluating ERP exercises | Doing ERP <br> Understanding the importance of repeated ERP exercises |
| 6. Values and Goals | Identifying and acting in accordance with personal values | Adding valued behaviours to weekly plan <br> Understanding the difference between values and goals |
| 7. Difficulties during treatment | Strategies to deal with common difficulties and setbacks | Problem-solving skills around common difficulties in ERP |
| 8. Summary and Relapse Prevention | Treatment summary, evaluation of treatment, and designing a relapse prevention plan | Understanding that improvements can happen after treatment <br> Understanding the role of continuous ERP in maintaining progress |

The emphasis is on doing exposure with response prevention (ERP), which we view as the main component of BDD-NET. We suggest that therapists encourage patients to progress through the first three modules as fast as possible (preferably in two weeks or less), check that they have understood the rationale for ERP, and then start doing ERP. Once patients are doing regular ERP-exercises, therapists can open up modules 6-7 for them to complete while continuing to do daily ERP. Module 8 can then be opened up with one to two weeks left in treatment.

## Closing remarks

The strategies outlined here should be viewed as the first building blocks in becoming an effective ICBT therapist using BDD-NET. As in regular clinical practice, we recommend continuous supervision and that therapists discuss difficult cases with colleagues.

We strive to continuously update and improve this material and would appreciate any feedback. You can reach us at <ocdnet.support@webcbt.se> or talk to us in person at a training session.