---
title: "BASS4 - ADMINISTRATOR’S MANUAL"
author: "Louise Serenhov, Erik Sjöstrand, Jenny-Li Örsell & Brjánn Ljótsson"
date: "Last updated `r Sys.Date()`, current BASS version: 4.9.3"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [bibliography.bib, packages.bib]
biblio-style: apalike
linkcitations: yes
github-repo: BASS-manual/manual
description: "Adminstrator`s manual for BASS4."
---

# Introduction

*Disclaimer: This manual is written primarily for full-access administrators in BASS. While you will find instructions and useful tips even if you’re not an administrator, note that all options described may not be available to you.*
In this manual you will learn how to manage participants, combine self-help material into treatments, keep track on events during an ongoing study/program, manage security and privacy settings, collect and export data and communicate with participants through the administration interface of BASS.

Should you have questions not yet answered by this manual, you're very welcome to contact us at `bass-support[at]ki.se`.

BASS is comprised of two main parts, or user interfaces: the administrator’s view and the participant’s view. These are part of the same database, but accessed through slightly different web addresses, URL:s.

1. The administrator’s view is accessed through the URL https://webcbt.se/YourDataBase or its variant https://bassdb.se/YourDataBase. 
2. The participant’s view is accessed through a similar URL: https://YourDataBase.webcbt.se or its corresponding variant https://YourDataBase.bassdb.se.
3. These different URL domains are presented as options for you to choose which one suits your project the best. A research project might not have much in common with CBT treatments, and as such the domain ”webcbt.se” might seem a little odd to participants. In such cases, the domain ”bassdb.se” might be more suitable. On the flip side, ”webcbt.se” might be a perfect fit in the case where CBT treatments are in fact the main part of your project.
4. BASS is a powerful and flexible tool specifically designed for online psychological research projects or treatment programs. It supports online registration, assessment, treatment as well as being able to provide detailed data reports.
5. BASS is currently used by a multitude of different research projects and treatments.
6. We offer active remote support accessed by mail, telephone and/or digital meetings such as Zoom, Microsoft Teams or similar applications. For clients located in Stockholm, Sweden and the surrounding area, we also offer in-person meetings at the Karolinska Institutet campus in Solna.